#!/bin/sh

echo 0 99999 > /proc/sys/net/ipv4/ping_group_range

ifconfig lo 127.0.0.1
ifconfig eth0 10.0.2.15
route add default gw 10.0.2.2

udhcpc

# Power button event
mkdir -p /etc/acpi/PWRF
echo '#!/bin/sh' > /etc/acpi/PWRF/00000080
echo 'poweroff' >> /etc/acpi/PWRF/00000080
chmod +x /etc/acpi/PWRF/00000080
acpid

# Setup dropbear ssh
touch /var/log/lastlog
dropbear -R -I 60 -E > /var/log/dropbear 2>&1

# Setup vsock server
echo "Run socat as vsock ssh proxyserver (port=${VSOCK_PORT})"
socat VSOCK-LISTEN:${VSOCK_PORT},reuseaddr,fork TCP:127.0.0.1:22 > /var/log/vsock-server 2>&1 &

