#!/bin/busybox sh

# Recursively resolve tty aliases like console or tty0
list_console_devices() {
        if ! [ -e /sys/class/tty/$1/active ]; then
                echo $1
                return
        fi
        for dev in $(cat /sys/class/tty/$1/active); do
                list_console_devices $dev
        done
}

setup_inittab_console(){
        term=vt100
        # Inquire the kernel for list of console= devices
        consoles="$(for c in console $KOPT_consoles; do list_console_devices $c; done)"
        for tty in $consoles; do
                # do nothing if inittab already have the tty set up
                if ! grep -q "^$tty:" /etc/inittab; then
                        echo "# enable login on alternative console" \
                                >> /etc/inittab
                        # Baudrate of 0 keeps settings from kernel
                        echo "$tty::respawn:/sbin/getty -L 0 $tty $term" \
                                >> /etc/inittab
                fi
                if [ -e /etc/securetty ] && ! grep -q -w "$tty" /etc/securetty; then
                        echo "$tty" >> /etc/securetty
                fi
        done
}

busybox rm /init
busybox mkdir -p /etc/network /etc/init.d /proc /root /sbin /sys /usr/bin /usr/sbin /tmp

/bin/busybox --install -s
export PATH=/usr/bin:/bin:/usr/sbin:/sbin

mount -t proc proc /proc
mount -t sysfs sysfs /sys

# See mdev.txt in busybox document
mdev -s

mount -t devtmpfs -o exec,nosuid,mode=0755,size=2M devtmpfs /dev 2>/dev/null \
        || mount -t tmpfs -o exec,nosuid,mode=0755,size=2M tmpfs /dev

# Make sure /dev/null is a device node. If /dev/null does not exist yet, the command
# mounting the devtmpfs will create it implicitly as an file with the "2>" redirection.
# The -c check is required to deal with initramfs with pre-seeded device nodes without
# error message.
[ -c /dev/null ] || mknod -m 666 /dev/null c 1 3

# Make sure /dev/kmsg is a device node. Writing to /dev/kmsg allows the use of the
# earlyprintk kernel option to monitor early init progress. As above, the -c check
# prevents an error if the device node has already been seeded.
[ -c /dev/kmsg ] || mknod -m 660 /dev/kmsg c 1 11

# pty device nodes (later system will need it)
[ -c /dev/ptmx ] || mknod -m 666 /dev/ptmx c 5 2
[ -d /dev/pts ] || mkdir -m 755 /dev/pts
mount -t devpts -o gid=5,mode=0620,noexec,nosuid devpts /dev/pts

# shared memory area (later system will need it)
[ -d /dev/shm ] || mkdir /dev/shm
mount -t tmpfs -o nodev,nosuid,noexec shm /dev/shm

hostname localhost

setup_inittab_console

exec /linuxrc
